# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jkmeansEM <- function(y, k, meansIni, steps = 1000L, tol = 1E-8, fixW = FALSE, useKmeansIni = FALSE, sigma2_ini = 0.1) {
    .Call('jkmeans_jkmeansEM', PACKAGE = 'jkmeans', y, k, meansIni, steps, tol, fixW, useKmeansIni, sigma2_ini)
}

rDARC <- function(Y, d, k, meansIni, steps = 1000L, tol = 1E-8, randomStart = TRUE, fixW = FALSE, useEstep = TRUE, sigma2_ini = 0.1, ver = 1L) {
    .Call('jkmeans_rDARC', PACKAGE = 'jkmeans', Y, d, k, meansIni, steps, tol, randomStart, fixW, useEstep, sigma2_ini, ver)
}

kmpp <- function(Y, k) {
    .Call('jkmeans_kmpp', PACKAGE = 'jkmeans', Y, k)
}

