// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// jkmeans
Rcpp::List jkmeans(const arma::mat& y, int k, int j, int steps);
RcppExport SEXP jkmeans_jkmeans(SEXP ySEXP, SEXP kSEXP, SEXP jSEXP, SEXP stepsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type steps(stepsSEXP);
    __result = Rcpp::wrap(jkmeans(y, k, j, steps));
    return __result;
END_RCPP
}
