# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jkmeansEM <- function(y, k, j, steps = 1000L, tol = 1E-8, fixW = TRUE, flexJ = FALSE, zetaTrunc = 0.01, useKmeansIni = TRUE, meansIni = 0L) {
    .Call('jkmeans_jkmeansEM', PACKAGE = 'jkmeans', y, k, j, steps, tol, fixW, flexJ, zetaTrunc, useKmeansIni, meansIni)
}

jkmeansEMBatch <- function(y, k, j, steps = 1000L, tol = 1E-8, fixW = TRUE, flexJ = FALSE, zetaTrunc = 0.01, useKmeansIni = TRUE, meansIni = 0L) {
    .Call('jkmeans_jkmeansEMBatch', PACKAGE = 'jkmeans', y, k, j, steps, tol, fixW, flexJ, zetaTrunc, useKmeansIni, meansIni)
}

