# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jkmeansEM <- function(y, k, j, steps = 1000L, tol = 1E-8) {
    .Call('jkmeans_jkmeansEM', PACKAGE = 'jkmeans', y, k, j, steps, tol)
}

jkmeansQNEM <- function(y, k, j, steps = 1000L) {
    .Call('jkmeans_jkmeansQNEM', PACKAGE = 'jkmeans', y, k, j, steps)
}

